mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8098
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/iotcloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    password: CkA4NAbqHCz@t
    username: iotcloud
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
beetl:
  templates-path: templates